services:
  db:

    container_name: employee
    image: postgres
    environment:
      POSTGRES_DB: employeeManagement
      POSTGRES_USER: fiskhumalo
      POSTGRES_PASSWORD: Prodolsk7
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5832:5432"
    networks:
      - db
    restart: unless-stopped

networks:
  db:
    driver: bridge

volumes:
  db: